#!/bin/bash

# find and replace a string from current directory down through sub-dirs

usage () {
    echo "find and replace strings recursively in current directory"
    echo "supply strings to find and replace, example usage:"
    echo "$0 foo bar"
    exit 1
}

# check argument count
if [[ $# != 2 ]]; then
    usage
fi

FIND=$1
REPLACE=$2

ack -l $FIND | xargs sed -i'' -e "s/$FIND/$REPLACE/g"
