#!/bin/bash -e

# Log memory usage on a node
#
# Print a header and then the memory usage statistics to stdout (comma separated output)
# Typical usage:
# $ log-host-memory-usage > memory.log
#
# Note that this logs the all the memory allocated on the host, not only your jobs
# You may request exclusive use of a node with the following sbatch directive:
# #SBATCH --exclusive
#
# plot-memory-usage may be used to plot the logged timeseries

echo "datetime,total,used,free,shared,buff/cache,available,swap_total,swap_used,swap_free"
while true; do
    DATETIME=$(date '+%Y-%m-%dT%H:%M:%S.%3N%:z')
    MEM=$(free -m | grep Mem: | sed 's/Mem://g')
    SWAP=$(free -m | grep Swap: | sed 's/Swap://g')
    echo "$DATETIME" "$MEM" "$SWAP" | sed -r "s/[[:space:]]+/,/g"
    sleep 0.25
done
