#! /usr/bin/bash

# for a given MS Access file, read using mdb-tools and write each table
# out as a CSV file

set -e

if [ -z $(which mdb-tables) ]; then
    echo "require executable mdb-tables, please install mdbtools package"
    exit 1
fi

if [ -z $1 ]; then
    echo "require path to Microsoft Access DB file as argument 1"
    exit 1
fi

MDB_FILE=$(basename -- "$1")
STEM="${MDB_FILE%.*}"
EXT="${MDB_FILE##*.}"

if [ $EXT != "mdb" ]; then
    echo "warning, database file extension is $EXT, not mdb"
fi

mkdir $STEM

for TABLE_NAME in $(mdb-tables $MDB_FILE); do
    mdb-export $MDB_FILE $TABLE_NAME > "${STEM}/${TABLE_NAME}.csv"
done

echo "exported table(s) to $STEM"
