#!/bin/bash -e

# print a header and then the memory usage statistics to stdout (comma separated output)
# typical usage:
# $ memory-log > memory.log

echo "datetime $(free -m | grep total | sed -E 's/^    (.*)/\1/g')" | sed -r "s/[[:space:]]+/,/g"
while true; do
    echo "$(date '+%Y-%m-%dT%H:%M:%S') $(free -m | grep Mem: | sed 's/Mem://g')" | sed -r "s/[[:space:]]+/,/g"
    sleep 1
done
