#!/bin/bash

set -e

NODATA=$(gdalinfo "$1" -json | jq .bands[0].noDataValue)
echo "Found nodata value $NODATA in raster $1"

# handle case of NODATA == nan - the JSON output of gdalinfo will change
# nan to "NaN" so we need to reverse that for gdal_calc.py
if [ "$NODATA" == '"NaN"' ]
then
  NODATA="nan"
fi

if [ "$NODATA" == 'null' ]
then
  NODATA="nan"
fi

if [ -z "$NODATA" ]
then
  NODATA="nan"
fi

gdal_calc.py \
  --quiet \
  -A "$1" \
  --outfile="$2" \
  --overwrite \
  --calc="numpy.where(A<=numpy.quantile(A,$3),$NODATA,A)" \
  --NoDataValue=$NODATA \
  --hideNoData

echo "Written raster with values less than quantile=$3 as $NODATA to $2"
