#!/bin/bash

#
# 20250531 F. Thomas
# This isn't actually seff, but it does something similar...
# Find properties of completed job
#

JOB_ID=$1
FIELDS="JobID,User,State,AllocCPUS,REQMEM,TotalCPU,Elapsed,MaxRSS,ExitCode,NNodes,NTasks"
{
    echo $FIELDS
    sacct -P -n -a --format $FIELDS -j $JOB_ID | sed "s/|/,/g"
} | column -s, -t
